local M = {}
M.WINDOW_RESIZED = "WINDOW_RESIZED"
M.STORAGE_CHANGED = "STORAGE_CHANGED"
M.STORAGE_SAVED = "STORAGE_SAVED"
M.SCENE_CHANGED = "SCENE_CHANGED"
M.JSTODEF = "JSTODEF"
M.WINDOW_EVENT = "WINDOW_EVENT"

M.RESOURCE_ADD = "RESOURCE_ADD"
M.RESOURCE_SPEND = "RESOURCE_SPEND"
M.RESOURCE_SPEND = "RESOURCE_SPEND"

M.TASK_COMPLETED = "TASK_COMPLETED"
M.TASK_VALUE_CHANGED = "TASK_VALUE_CHANGED"


return M